#!/bin/bash
xgettext --language=Python --keyword=_ --output=po/tuquito-control-center.pot usr/lib/tuquito/tuquito-control-center/control-center.py usr/lib/tuquito/tuquito-control-center/suggestions.py --from-code=utf-8
cd po
msgmerge es.po tuquito-control-center.pot -o es.po
msgmerge pt.po tuquito-control-center.pot -o pt.po
