#!/bin/bash
xgettext --language=Python --keyword=_ --output=po/emmi-control-center.pot usr/lib/emmi/emmi-control-center/control-center.py usr/lib/emmi/emmi-control-center/suggestions.py translations.py --from-code=utf-8
cd po
msgmerge es.po emmi-control-center.pot -o es.po
msgmerge pt.po emmi-control-center.pot -o pt.po
