#!/bin/sh
# postinst script for Garfio 2.1
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
	if [ -f /tmp/gnomecc.desktop ]; then
		cp /tmp/gnomecc.desktop /usr/share/applications/gnomecc.desktop
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "argumentos \`$1'" >&2
        exit 1
    ;;
esac

exit 0
